begin
  if (Product.present? and not Product.exists?)
    category = Category.find_by name: 'chapeaux'
    Product.create([
      { category_id:  category.id,
        name:         'beanie_swamp', 
        title:        'Болотная шапка бини из конопли',
        code:         'bea-001-01',
        price:        888.00,
        quantity:     12,
        vendor_code:  'ht-hc-099',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная, цвет - болотный',
        url:          'bolotnaya-shapka-bini-iz-konopli',
        seo_title:    'Болотная шапка бини из конопли'
      },
      { category_id:  category.id,
        name:         'beanie_burgundy', 
        title:        'Бордовая шапка бини из конопли',
        code:         'bea-002-01',
        price:        888.00,
        quantity:     9,
        vendor_code:  'ht-c-092',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная, цвет - бордовый',
        url:          'bordovaya-shapka-bini-iz-konopli',
        seo_title:    'Бордовая шапка бини из конопли'
      },
      { category_id:  category.id,
        name:         'beanie_unpainted', 
        title:        'Неокрашенная шапка бини из конопли',
        code:         'bea-003-01',
        price:        888.00,
        quantity:     0,
        vendor_code:  'ht-hc-999',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная неокрашенная',
        url:          'neokrashennaya-shapka-bini-iz-konopli',
        seo_title:    'Неокрашенная шапка бини из конопли'
      },
      { category_id:  category.id,
        name:         'beanie_yellow', 
        title:        'Желтая шапка бини из конопли',
        code:         'bea-004-01',
        price:        888.00,
        quantity:     17,
        vendor_code:  'ht-hc-091',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная желтая',
        url:          'zhyoltaya-shapka-bini-iz-konopli',
        seo_title:    'Желтая шапка бини из конопли'
      },
      { category_id:  category.id,
        name:         'beanie_darkgreen', 
        title:        'Тёмно-зелёная шапка бини из конопли',
        code:         'bea-005-01',
        price:        888.00,
        quantity:     5,
        vendor_code:  'ht-hc-089',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная конопляная',
        url:          'vsesezonnaya-tyomno-zelyonaya-shapochka-bini-iz-konopli',
        seo_title:    'Тёмно-зелёная шапка бини из конопли'
      },
      { category_id:  category.id,
        name:         'beanie_violet', 
        title:        'Шапка бини из конопли Violet',
        code:         'bea-006-01',
        price:        888.00,
        quantity:     0,
        vendor_code:  'ht-hc-101',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная конопляная',
        url:          'shapka-bini-iz-konopli-violet',
        seo_title:    'Шапка бини из конопли Violet'
      },
      { category_id:  category.id,
        name:         'beanie_blue', 
        title:        'Голубая шапка бини из конопли',
        code:         'bea-007-01',
        price:        888.00,
        quantity:     8,
        vendor_code:  'ht-hc-003',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная конопляная',
        url:          'golubaya-shapka-bini-iz-konopli',
        seo_title:    'Голубая шапка бини из конопли'
      },
      { category_id:  category.id,
        name:         'beanie_violet', 
        title:        'Шапка бини из конопли Ван Гог',
        code:         'bea-008-01',
        price:        888.00,
        quantity:     20,
        vendor_code:  'ht-hc-018',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная конопляная',
        url:          'shapka-bini-iz-konopli-van-gog',
        seo_title:    'Шапка бини из конопли Ван Гог'
      },
      { category_id:  category.id,
        name:         'beanie_knitted', 
        title:        'Вязаная шапка бини "Джагат" раста',
        code:         'bea-009-01',
        price:        1488.00,
        quantity:     11,
        vendor_code:  'ht-hwbc-11',
        vendor_price: 708.00,
        abstract:     'Шапка зимняя конопляная',
        url:          'vyazanaya-shapka-bini-dzhagat-rasta',
        seo_title:    'Вязаная шапка бини Джагат раста'
      },
      { category_id:  category.id,
        name:         'chapeau_darkblue', 
        title:        'Шапка из конопли Dark Blue',
        code:         'cha-001-01',
        price:        888.00,
        quantity:     15,
        vendor_code:  'ht-hc-009',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная коноплянная',
        url:          'shapka-iz-konopli-dark-blue',
        seo_title:    'Шапка из конопли Dark Blue'
      },
      { category_id:  category.id,
        name:         'chapeau_lightorange', 
        title:        'Шапка из конопли Light orange',
        code:         'cha-002-01',
        price:        888.00,
        quantity:     7,
        vendor_code:  'ht-hc-008',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная коноплянная',
        url:          'shapka-iz-konopli-light-orange',
        seo_title:    'Шапка из конопли Light orange'
      },
      { category_id:  category.id,
        name:         'chapeau_deepforest', 
        title:        'Шапка из конопли Deep Forest',
        code:         'cha-003-01',
        price:        888.00,
        quantity:     16,
        vendor_code:  'ht-hc-013',
        vendor_price: 350.00,
        abstract:     'Шапка всесезонная коноплянная',
        url:          'shapka-iz-konopli-deep-forest',
        seo_title:    'Шапка из конопли Deep Forest'
      }
    ]) 

    puts "===== 'Product' #{Product.count}record(s) created"
  else
    puts "===== 'Product' seeding skipped"
  end
rescue
  puts "----- Achtung! Something went wrong ('Product' entity does not exist?)"
end